package com.bankingsystem.controller.form;

import lombok.Data;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.NotNull;
import java.math.BigDecimal;

@Data
public class LoanForm {
    @NotNull(message = "Loan amount is required")
    @DecimalMin(value = "0.01", message = "Loan amount must be greater than 0")
    private BigDecimal amount;
    
    @NotNull(message = "Interest rate is required")
    @DecimalMin(value = "0.01", message = "Interest rate must be greater than 0")
    private BigDecimal interestRate;
    
    @NotNull(message = "Loan term is required")
    @DecimalMin(value = "1", message = "Loan term must be at least 1 month")
    private Integer termMonths;
    
    // Getters and setters are generated by Lombok @Data
}
